language: r

matrix:
  include:
    - dist: xenial
      r: release
      after_success: Rscript -e 'covr::codecov()'
    - dist: trusty
      r: devel
    - os: osx
      r: release

sudo: false

cache: packages
warnings_are_errors: true
r_check_args: "--as-cran"
